version: "3.9"
services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    volumes: ["./backend:/app", "./frontend/dist:/app/static"]
    environment:
      - UVICORN_PORT=8000
  frontend:
    build: ./frontend
    ports: ["8080:80"]
    depends_on: ["backend"]
